import { NextResponse, type NextRequest } from "next/server";
import { renderToBuffer } from "@react-pdf/renderer";
import React from "react";
import { Resend } from "resend";
import { createAdminSupabase } from "@/lib/supabase/admin";
import {
  isAuthorizedCron,
  isAutomationEnabled,
  yesterdayEasternDate,
} from "@/lib/cron-auth";
import { DailyReportPDF } from "@/lib/pdf/DailyReport";
import { loadDailyReportData } from "@/lib/pdf/data";
import { fetchWildwoodWeather } from "@/lib/weather";
import { fetchDailyMetrics } from "@/lib/snowflake";
import {
  renderDailyReportEmailHTML,
  renderDailyReportEmailText,
} from "@/lib/email/dailyReport";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

/**
 * Runs at 1:30 AM. If a daily report has already been sent for the day
 * that just ended, do nothing. Otherwise, auto-generate a minimal
 * "Nothing to report" PDF with current weather + metrics, send it to
 * recipients, and mark the daily report as sent.
 */
export async function GET(request: NextRequest) {
  return handle(request);
}
export async function POST(request: NextRequest) {
  return handle(request);
}

async function handle(request: NextRequest) {
  if (!isAuthorizedCron(request)) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const supabase = createAdminSupabase();
  const enabled = await isAutomationEnabled(supabase);
  if (!enabled) {
    return NextResponse.json({
      ok: true,
      skipped: true,
      reason: "automation disabled",
    });
  }

  const date = yesterdayEasternDate();

  // Get-or-create the daily_report row for that date using the SECURITY
  // DEFINER RPC. (Admin client bypasses RLS, so this just runs.)
  const { data: drRow } = await supabase
    .from("daily_reports")
    .select("id, status, supervisor_notes, ai_summary")
    .eq("report_date", date)
    .maybeSingle();

  let drId: string | null = drRow?.id ?? null;
  if (!drId) {
    const { data: created } = await supabase
      .from("daily_reports")
      .insert({ report_date: date, status: "draft" })
      .select("id")
      .single();
    drId = created?.id ?? null;
  }
  if (!drId) {
    return NextResponse.json(
      { error: "could not create or load daily report" },
      { status: 500 },
    );
  }

  // Bail out if a real Daily Report was already sent.
  const { data: drStatus } = await supabase
    .from("daily_reports")
    .select("status")
    .eq("id", drId)
    .single();

  if (drStatus?.status === "sent") {
    await supabase.from("audit_log").insert({
      action: "cron.fallback_skipped",
      entity_type: "daily_report",
      entity_id: drId,
      meta: { reason: "already sent", run_date: date },
    });
    return NextResponse.json({
      ok: true,
      skipped: true,
      reason: "daily report already sent",
      run_date: date,
    });
  }

  // Refresh weather + metrics so the fallback report is meaningful.
  try {
    const weather = await fetchWildwoodWeather(date);
    await supabase
      .from("daily_reports")
      .update({ weather_snapshot: weather })
      .eq("id", drId);
  } catch {
    /* non-fatal */
  }

  try {
    const metrics = await fetchDailyMetrics(date);
    await supabase
      .from("daily_reports")
      .update({ metrics_snapshot: metrics })
      .eq("id", drId);
  } catch {
    /* non-fatal */
  }

  // Set the AI summary to the fallback message (only if empty).
  if (!drRow?.ai_summary || drRow.ai_summary.trim().length === 0) {
    await supabase
      .from("daily_reports")
      .update({
        ai_summary:
          "Nothing to report — this Daily Report was auto-generated by the overnight fallback because no supervisor sent a manual report for this date.",
      })
      .eq("id", drId);
  }

  // Load the fully-populated data for PDF rendering.
  const data = await loadDailyReportData(date);
  if (!data) {
    return NextResponse.json(
      { error: "could not load daily report data for PDF" },
      { status: 500 },
    );
  }

  // Recipients
  const { data: recipients } = await supabase
    .from("email_recipients")
    .select("name, email")
    .eq("active", true);
  if (!recipients || recipients.length === 0) {
    await supabase.from("audit_log").insert({
      action: "cron.fallback_skipped",
      entity_type: "daily_report",
      entity_id: drId,
      meta: { reason: "no active recipients", run_date: date },
    });
    return NextResponse.json({
      ok: true,
      skipped: true,
      reason: "no active recipients",
      run_date: date,
    });
  }

  // Render PDF
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const buffer: Buffer = await renderToBuffer(
    React.createElement(DailyReportPDF, { data }) as unknown as any,
  );

  // Send email via Resend
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: "RESEND_API_KEY not set" },
      { status: 503 },
    );
  }
  const resend = new Resend(apiKey);
  const from =
    process.env.RESEND_FROM_EMAIL ||
    "beAcon Operational Intelligence <onboarding@resend.dev>";

  const sendResult = await resend.emails.send({
    from,
    to: recipients.map((r) => r.email),
    subject: `beAcon · Daily Report — Morey's Piers · ${date} (Auto)`,
    text: renderDailyReportEmailText(data, { fallback: true }),
    html: renderDailyReportEmailHTML(data, { fallback: true }),
    attachments: [
      {
        filename: `morey-daily-${date}-auto.pdf`,
        content: buffer,
      },
    ],
  });

  if (sendResult.error) {
    return NextResponse.json(
      { error: sendResult.error.message || "send failed" },
      { status: 502 },
    );
  }

  // Snapshot + mark sent
  const snapshot = {
    reports: data.reports,
    weather: data.weather,
    metrics: data.metrics,
    ai_summary: data.ai_summary,
    supervisor_notes: data.supervisor_notes,
    curator: null,
    sent_message_id: sendResult.data?.id ?? null,
    fallback: true,
  };

  await supabase.rpc("mark_daily_report_sent", {
    p_id: drId,
    p_recipients: recipients,
    p_snapshot: snapshot,
  });

  await supabase.from("audit_log").insert({
    action: "cron.fallback_sent",
    entity_type: "daily_report",
    entity_id: drId,
    meta: {
      recipients: recipients.map((r) => r.email),
      message_id: sendResult.data?.id,
      run_date: date,
    },
  });

  return NextResponse.json({
    ok: true,
    sent: true,
    run_date: date,
    recipients_count: recipients.length,
    message_id: sendResult.data?.id,
  });
}
